### PR TITLE
👁️ make initPromise visible

### PR DESCRIPTION
**Pull request by Aldhanekaa**
It's unclear how to clearly knows whether if it has succeeded fetched the Google Bard SNlM0e, so by making `initPromise` visible aims for user to clearly know whether the library has fetched the Google Bard SNlM0e.

### CODE REVIEW

**Comment by ThatXliner** [comment]
Actually, I would like to bring this further: **bring _all_ the private variables public**. That way if someone really needs to tinker with the internals, then they don't have to wait on a new release (or their own custom fork). Remember, if it's never mentioned in the documentation, it's an implementation detail that should not be relied on

This principle is especially prevalent in the Python community where private variables/properties do not exist.

**Comment by EvanZhouDev** [comment]
Interesting. @Aldhanekaa I agree with @ThatXliner... what do you think?

**Comment by Aldhanekaa** [comment]
> Interesting. @Aldhanekaa I agree with @ThatXliner... what do you think?

Agree with this! I also consent with header variable being private, because, maybe there will be more header key to access Google Bard API.

**Comment by Aldhanekaa** [comment]
I agree with the idea, but do you guys think `fetch` private variable shall be public?

**Comment by ThatXliner** [comment]
I think both `verbose` and `fetch` could have their official APIs to be patching the JS object. The best API is no API

**Comment by Aldhanekaa** [comment]
Sorry I don't quiet get what you mean, does that mean both `verbose` and `fetch` shall be public?

**Comment by ThatXliner** [comment]
https://github.com/Aldhanekaa/bard-ai/blob/10ee8563b1f0f223b0569a4ba887be9d8e512dab/index.js#L24-L25

Imagine if these settings weren't part of the config but in fact the way to change it is to patch the JS object (modify the properties after instantiation)

**Comment by EvanZhouDev** [comment]
:shipit: Looks good to me!

**Pull request merged**
