### PR TITLE
✨ Better Typescript Support

### PR DESCRIPTION
**Pull request by RFS-ADRENO**
There were a few errors while using with Typescript so... I fixed them!

### CODE REVIEW

**Comment by EvanZhouDev** [comment]
Amazing! Thank you so much! I'm not the best at TS myself, so I've had to rely on some amazing contributors :)

**Comment by EvanZhouDev** [comment]
I accidentally squashed the commits on merge, I'm trying to fix it so that you're included in the contributors list...

**Comment by EvanZhouDev** [comment]
Okay... it's not the cleanest solution, but you're now added as a contributor :)

**Comment by EvanZhouDev** [comment]
Do you happen to have Slack? Feel free to join the new `bard-ai` Slack channel [here](https://join.slack.com/t/bard-aiworkspace/shared_invite/zt-1y1g3570m-Hx_N3IShMYBMkR6jpRyRjw).

**Comment by RFS-ADRENO** [comment]
Alright I will, thanks 🥳!

**Comment by EvanZhouDev** [comment]
Hello @RFS-ADRENO, can you please take a look at https://github.com/EvanZhouDev/bard-ai/issues/19 and perhaps see why it's not working for the user? Thanks!

**Comment by RFS-ADRENO** [comment]
@EvanZhouDev I think he is still using the version from NPM

**Comment by EvanZhouDev** [comment]
Oh! I forgot to push that version to NPM! I'll do that right now...
Again, feel free to check out the Slack workspace once in a while, as we talk about the project there 🙂
No pressure if you are working on other things!

**Comment by EvanZhouDev** [comment]
By the way, you can turn on Slack notifications in settings if you need to, they may be off by default if you're not getting DMs and mentions.

**Comment by EvanZhouDev** [comment]
> Will you be interested in helping with types in the upcoming bard-ai versions as well? We are expecting some minor to
> major API changes, and I would love to have you along in the process too!

Don't know if you're still here, but `bard-ai` v2 is almost ready... if you want to, feel free to help us out with the types 😅

**Comment by RFS-ADRENO** [comment]
> > Will you be interested in helping with types in the upcoming bard-ai versions as well? We are expecting some minor to
> > major API changes, and I would love to have you along in the process too!
> 
> Don't know if you're still here, but `bard-ai` v2 is almost ready... if you want to, feel free to help us out with the types 😅

sure!

**Comment by EvanZhouDev** [comment]
Thank you, it’s greatly appreciated; I’m sure you know, but just in case, you can find the code on the `v2` branch :)

**Pull request merged**
